---
- name: Provisioning VM with Docker
  hosts: client
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Clone GitHub Repository
      git:
        repo: https://github.com/mustapha75000/pokedex
        dest: /home/vagrant/app

    - name: Build Docker Image
      docker_image:
        name: mon-site-web
        tag: latest
        build:
         path: /home/vagrant/projet-ansible
         dockerfile: Dockerfile
      become: true

    - name: Run Docker Container
      docker_container:
        name: mon-site-web-container
        image: mon-site-web
        state: started
        ports:
          - "80:80"